import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import ResponsiveAppBar from '@/components/layout/Appbar';
import Footer from "@/components/layout/Footer";


export const metadata: Metadata = {
  title: "Create Next App ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppRouterCacheProvider options={{ key: 'css' }}>
      <ThemeProvider theme={theme}>
       <body>
        <ResponsiveAppBar/>
          {children}
          <Footer/>
        </body>
       
        </ThemeProvider>
      </AppRouterCacheProvider>
      
    </html>
  );
}
